version: "3"

services:
  postgres:
    image: postgres:latest
    constainer_name: stockly-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    valuemes:
      - ./.postgres-data:/var/lib/postgres/data

valumes:
  .postgres-data: