import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Recursos Básicos do NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>Main</main>
      <section>Section</section>
    </div>
  )
}
